function bass1 () {
    music.playTone(233, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(233, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(175, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(208, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(220, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(233, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(233, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(175, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(208, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(220, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
}
function dance () {
    led.unplot(3, 0)
    led.unplot(3, 1)
    led.unplot(0, 2)
    led.unplot(4, 4)
    led.plot(1, 0)
    led.plot(2, 0)
    led.plot(1, 1)
    led.plot(2, 1)
    led.plot(2, 2)
    led.plot(4, 2)
    led.plot(0, 3)
    led.plot(1, 3)
    led.plot(2, 3)
    led.plot(3, 3)
    led.plot(4, 3)
    led.plot(0, 4)
    led.plot(2, 4)
    basic.pause(music.beat(BeatFraction.Half))
    for (let index = 0; index < 2; index++) {
        led.toggle(1, 1)
        led.toggle(4, 1)
        led.toggle(0, 2)
        led.toggle(1, 2)
        led.toggle(3, 2)
        led.toggle(1, 3)
        led.toggle(3, 3)
        led.toggle(4, 3)
        led.toggle(0, 4)
        basic.pause(music.beat(BeatFraction.Half))
    }
    led.toggle(0, 0)
    led.toggle(2, 0)
    led.toggle(0, 1)
    led.toggle(2, 1)
    led.toggle(1, 2)
    led.toggle(2, 2)
    led.toggle(3, 2)
    led.toggle(4, 2)
    led.toggle(4, 3)
    led.toggle(0, 4)
    led.toggle(1, 4)
    led.toggle(2, 4)
    basic.pause(music.beat(BeatFraction.Half))
    led.toggle(0, 0)
    led.toggle(2, 0)
    led.toggle(0, 1)
    led.toggle(2, 1)
    led.toggle(3, 2)
    led.toggle(3, 4)
    basic.pause(music.beat(BeatFraction.Half))
    for (let index = 0; index < 2; index++) {
        led.toggle(2, 1)
        led.toggle(0, 2)
        led.toggle(2, 2)
        led.toggle(3, 2)
        led.toggle(0, 3)
        led.toggle(2, 3)
        led.toggle(3, 4)
        basic.pause(music.beat(BeatFraction.Half))
    }
    led.toggle(1, 0)
    led.toggle(3, 0)
    led.toggle(1, 1)
    led.toggle(3, 1)
    led.toggle(0, 2)
    led.toggle(1, 2)
    led.toggle(2, 2)
    led.toggle(4, 3)
    led.toggle(1, 4)
    led.toggle(2, 4)
    led.toggle(3, 4)
    led.toggle(4, 4)
    basic.pause(music.beat(BeatFraction.Half))
}
music.setTempo(130)
basic.showLeds(`
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    . . . . .
    `)
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(831, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(831, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Half))
        music.rest(music.beat(BeatFraction.Half))
        music.playTone(831, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(784, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(622, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(622, music.beat(BeatFraction.Quarter))
        music.playTone(698, music.beat(BeatFraction.Half))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(523, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Half))
        music.rest(music.beat(BeatFraction.Quarter))
        bass1()
    }
})
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        led.plot(1, 0)
        led.plot(3, 0)
        led.plot(0, 2)
        led.plot(1, 2)
        led.plot(2, 2)
        led.plot(3, 2)
        led.plot(4, 2)
        led.plot(1, 3)
        led.plot(2, 3)
        led.plot(3, 3)
        for (let index = 0; index < 2; index++) {
            basic.pause(music.beat(BeatFraction.Quarter))
            led.toggle(0, 0)
            led.toggle(1, 0)
            led.toggle(2, 0)
            led.toggle(3, 0)
            led.toggle(4, 2)
            led.toggle(0, 3)
            led.toggle(0, 4)
            led.toggle(1, 4)
            led.toggle(2, 4)
        }
        basic.pause(music.beat(BeatFraction.Quarter))
        for (let index = 0; index < 2; index++) {
            led.toggle(1, 0)
            led.toggle(2, 0)
            led.toggle(3, 0)
            led.toggle(4, 0)
            led.toggle(0, 2)
            led.toggle(4, 3)
            led.toggle(2, 4)
            led.toggle(3, 4)
            led.toggle(4, 4)
            basic.pause(music.beat(BeatFraction.Half))
        }
        for (let index = 0; index < 2; index++) {
            led.toggle(0, 0)
            led.toggle(1, 0)
            led.toggle(2, 0)
            led.toggle(3, 0)
            led.toggle(4, 2)
            led.toggle(0, 3)
            led.toggle(0, 4)
            led.toggle(1, 4)
            led.toggle(2, 4)
            basic.pause(music.beat(BeatFraction.Half))
        }
        for (let index = 0; index < 2; index++) {
            led.toggle(1, 0)
            led.toggle(2, 0)
            led.toggle(3, 0)
            led.toggle(4, 0)
            led.toggle(0, 2)
            led.toggle(4, 3)
            led.toggle(2, 4)
            led.toggle(3, 4)
            led.toggle(4, 4)
            basic.pause(music.beat(BeatFraction.Half))
        }
        basic.clearScreen()
        dance()
        basic.clearScreen()
    }
})
basic.forever(function () {
	
})
